name: usegalaxy-eu-website
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ca-certificates
  - pyzotero=1
  - bibtexparser=1
  - ruby=2.6
  - python-frontmatter=1
  - pandas=2
  - requests=2

